version: '3.9'
services:
  layer:
    build: .
    image: lambda_layer:latest
    platform: {{data.platform}}
    container_name: lambda-layer
    networks:
      - lambda-layer
    environment:
      - PYTHON_VERSION=python{{data.python_version}}
      - FILENAME=my_layer.zip
    entrypoint: /layer/create_layer.sh
    volumes:
      - ./requirements.txt:/layer/requirements.txt
      - ./build:/layer/build
networks:
  lambda-layer:
